---
title: "R Notebook"
output:
  html_notebook:
    highlight: tango
  html_document:
    df_print: paged
    highlight: tango
---

```{r Setup}
install.packages("rvest", dependencies = TRUE)
install.packages("countrycode", dependencies = TRUE)
install.packages("data.table", dependencies = TRUE)

library(tidyverse)
library(dplyr)
library(tidyr)
library(purrr)
library(xml2)
library(data.table)
library(rvest)
library(countrycode)
```


***

```{r Scrape Prison Data}
# Store web url
url <- read_html("http://www.prisonstudies.org/highest-to-lowest/prison_population_rate?field_region_taxonomy_tid=All")

#Scrape the website for prison population data
prison_population <- url %>% 
  html_nodes("#views-aggregator-datatable") %>%
  html_table() %>% 
  .[[1]] %>% 
  select("Title", "Prison Population Rate") %>% 
  mutate(country = 
           countrycode(.data$"Title", "country.name", "country.name", 
                       warn = FALSE)) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$country, "country.name", "wb", 
                       warn = FALSE)) %>% 
  rename(prison.pop.100k = "Prison Population Rate") %>% 
  drop_na() %>% 
  distinct(country, .keep_all = TRUE) %>% 
  select(wb.countrycode, prison.pop.100k)

bosnia_per100k <- round((1883 + 940) / (3.517*10))
united_kingdom_per100k <- round((85348 + 7611 + 1507) / (65.64*10))

prison_population$prison.pop.100k[prison_population$wb.countrycode == "GBR"] <- 
  united_kingdom_per100k
prison_population$prison.pop.100k[prison_population$wb.countrycode == "BIH"] <- 
  bosnia_per100k

write.csv(prison_population, file = "datasets/prison_population.csv")
```

***

```{r Extract Population Data}
population_2015 <- fread("datasets/API_SP.POP.TOTL_DS2_en_csv_v2_9984924.csv", 
                               header = TRUE, sep = ",", skip = 4, 
                    select = c("Country Name", "2015")) %>% 
  mutate(country = 
           countrycode(.data$"Country Name", 'country.name', 'country.name', 
                       warn = FALSE)) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$"Country Name", 'country.name', 'wb', 
                       warn = FALSE)) %>% 
  drop_na() %>% 
  rename(pop.2015 = "2015") %>% 
  select(country, wb.countrycode, pop.2015)

```

***

```{r Extract Happiness Scores}
happiness_2015 <- fread("datasets/Happiness rank and scores by country 2015 Kaggle.csv", 
                        header = TRUE, sep = ",", 
                        select = c("Country", "Happiness Score")) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$"Country", 'country.name', 'wb', 
                       warn = FALSE)) %>% 
  rename(happiness.score = "Happiness Score") %>% 
  distinct(wb.countrycode, .keep_all = TRUE) %>% 
  select(wb.countrycode, happiness.score)
```

***

```{r Extract Homicide Estimates}
homicide_2015 <- fread("datasets/Homicide Estimates  by country WHO.csv", 
                        header = FALSE, sep = ",", skip = 3, 
                        select = c(1, 3)) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$V1, 'country.name', 'wb', 
                       warn = FALSE)) %>% 
  rename(homicide.per100k = V3) %>% 
  select(wb.countrycode, homicide.per100k)
```

***

```{r Extract HDI Data}
human_dev_index_2015 <- fread("datasets/Human development index (HDI).csv", 
                        header = TRUE, sep = ",", skip = 1, 
                        select = c("Country", "2015")) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$Country, 'country.name', 'wb', 
                       warn = FALSE)) %>% 
  rename(hdi.2015 = "2015") %>% 
  select(wb.countrycode, hdi.2015)
```

***

```{r Extract Mean Years of Schooling Data}
years_schooling_2015 <- fread("datasets/Mean years of schooling (years).csv", 
                        header = TRUE, sep = ",", skip = 1, 
                        select = c("Country", "2015")) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$Country, 'country.name', 'wb', 
                       warn = FALSE)) %>% 
  rename(years.schooling = "2015") %>% 
  select(wb.countrycode, years.schooling)
```

***

```{r Extract Suicide Rates Data}
suicide_2015 <- fread("datasets/Suicide mortality rate by country WHO.csv", 
                        header = FALSE, sep = ",", skip = 3, 
                        select = c(1, 3)) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$V1, 'country.name', 'wb', 
                       warn = FALSE)) %>% 
  rename(suicide.per100k = V3) %>% 
  select(wb.countrycode, suicide.per100k)
```

***

```{r Extract Alcohol Consumption Data}
alcohol_2015 <- fread("datasets/alcohol_per_capita_consumption.csv", header = FALSE,
                 skip = 2, select = c(1, 4)) %>% 
  rename(country = V1, consumption.percapita = V4) %>% 
  mutate(wb.countrycode = 
           countrycode(.data$country, 'country.name', 'wb', 
                       warn = FALSE)) %>% 
  select(wb.countrycode, consumption.percapita) %>% 
  drop_na()
```

***

```{r Merge Datasets}
happiness_indicators0 <- list(population_2015, happiness_2015, human_dev_index_2015, years_schooling_2015, suicide_2015, homicide_2015, prison_population, alcohol_2015) %>% 
  reduce(inner_join, by = "wb.countrycode")

happiness_indicators <- subset(happiness_indicators0, pop.2015 > 1e6) 

write.csv(happiness_indicators, file = "datasets/happiness_indicators.csv")

```

